import { simple } from "./shared";
import type { Connector } from "./types";

export const analyticsConnectors: Connector[] = [
  simple({
    id: "clickhouse",
    name: "ClickHouse",
    logoSrc: "/logos/databases/clickhouse.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Real-time OLAP database",
    category: "analytics",
    dialect: "clickhouse",
    port: "9000",
  }),
  simple({
    id: "trino",
    name: "Trino",
    logoSrc: "/logos/databases/trino.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Distributed SQL query engine",
    category: "analytics",
    dialect: "trino",
    port: "8080",
  }),
  simple({
    id: "cratedb",
    name: "CrateDB",
    logoSrc: "/logos/databases/cratedb.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Distributed SQL for time series",
    category: "analytics",
    dialect: "crate",
    port: "4200",
  }),
  simple({
    id: "teradata",
    name: "Teradata",
    logoSrc: "/logos/databases/teradata.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Enterprise data warehouse",
    category: "analytics",
    dialect: "teradatasql",
    port: "1025",
  }),
  simple({
    id: "monetdb",
    name: "MonetDB",
    logoSrc: "/logos/databases/monetdb.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Column-store for analytics",
    category: "analytics",
    dialect: "monetdb",
    port: "50000",
  }),
  simple({
    id: "druid",
    name: "Apache Druid",
    logoSrc: "/logos/databases/druid.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Real-time analytics database",
    category: "analytics",
    dialect: "druid",
    port: "8082",
  }),
  simple({
    id: "impala",
    name: "Apache Impala",
    logoSrc: "/logos/databases/impala.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "MPP SQL engine for Hadoop",
    category: "analytics",
    dialect: "impala",
    port: "21050",
  }),
  simple({
    id: "drill",
    name: "Apache Drill",
    logoSrc: "/logos/databases/drill.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Schema-free SQL for files and DBs",
    category: "analytics",
    dialect: "drill",
    port: "8047",
  }),
  simple({
    id: "elasticsearch",
    name: "Elasticsearch",
    logoSrc: "/logos/databases/elasticsearch.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Distributed search and analytics engine",
    category: "analytics",
    dialect: "elasticsearch",
    port: "9200",
  }),
  {
    id: "duckdb",
    name: "DuckDB",
    logoSrc: "/logos/databases/duckdb.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "In-process OLAP SQL database",
    category: "analytics",
    dialect: "duckdb",
    template: "file",
    fields: [
      {
        name: "dbPath",
        label: "Database File Path",
        type: "text",
        required: true,
        placeholder: "/path/to/database.duckdb",
        defaultValue: ":memory:",
      },
    ],
    buildUrl: (d) => `duckdb:///${d.dbPath}`,
    buildDisplayUrl: (d) => `duckdb:///${d.dbPath}`,
    pasteModePlaceholder: "duckdb:///path/to/database.duckdb",
  },
  simple({
    id: "hive",
    name: "Apache Hive",
    logoSrc: "/logos/databases/hive.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Data warehouse on Hadoop",
    category: "analytics",
    dialect: "hive",
    port: "10000",
  }),
  simple({
    id: "dremio",
    name: "Dremio",
    logoSrc: "/logos/databases/dremio.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Data lakehouse query engine",
    category: "analytics",
    dialect: "dremio",
    port: "9047",
  }),
  simple({
    id: "pinot",
    name: "Apache Pinot",
    logoSrc: "/logos/databases/pinot.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Real-time OLAP for user-facing analytics",
    category: "analytics",
    dialect: "pinot",
    port: "9000",
  }),
  simple({
    id: "solr",
    name: "Apache Solr",
    logoSrc: "/logos/databases/solr.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Enterprise search and analytics platform",
    category: "analytics",
    dialect: "solr",
    port: "8983",
  }),
];
