import { simple } from "./shared";
import type { Connector } from "./types";

export const specialtyConnectors: Connector[] = [
  simple({
    id: "sybase",
    name: "SAP Sybase ASE",
    logoSrc: "/logos/databases/sybase.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "SAP enterprise RDBMS",
    category: "enterprise",
    dialect: "sybase",
    port: "5000",
  }),
  simple({
    id: "sqlany",
    name: "SQL Anywhere",
    logoSrc: "/logos/databases/sqlany.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "SAP embedded and remote database",
    category: "enterprise",
    dialect: "sqlany",
    port: "2638",
  }),
  {
    id: "access",
    name: "Microsoft Access",
    logoSrc: "/logos/databases/access.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Desktop relational database",
    category: "enterprise",
    dialect: "access+pyodbc",
    template: "file",
    fields: [
      {
        name: "dbPath",
        label: "Database File Path",
        type: "text",
        required: true,
        placeholder: "C:/path/to/database.accdb",
      },
    ],
    buildUrl: (d) => `access+pyodbc:///${d.dbPath}`,
    buildDisplayUrl: (d) => `access+pyodbc:///${d.dbPath}`,
    pasteModePlaceholder: "access+pyodbc:///C:/path/to/database.accdb",
  },
  simple({
    id: "mimer",
    name: "Mimer SQL",
    logoSrc: "/logos/databases/mimer.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "ACID-compliant embedded/server database",
    category: "enterprise",
    dialect: "mimer",
    port: "1360",
  }),
  {
    id: "firebird",
    name: "Firebird",
    logoSrc: "/logos/databases/firebird.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Open-source cross-platform RDBMS",
    category: "relational",
    dialect: "firebird",
    fields: [
      {
        fields: [
          {
            name: "host",
            label: "Host",
            type: "text",
            required: true,
            placeholder: "db.example.com",
          },
          {
            name: "port",
            label: "Port",
            type: "text",
            required: true,
            defaultValue: "3050",
          },
        ],
        gridCols: "grid-cols-[1fr_100px]",
      },
      {
        name: "database",
        label: "Database path",
        type: "text",
        required: true,
        placeholder: "/var/lib/firebird/data/mydb.fdb",
      },
      {
        fields: [
          {
            name: "username",
            label: "Username",
            type: "text",
            required: true,
            placeholder: "SYSDBA",
          },
          {
            name: "password",
            label: "Password",
            type: "password",
            required: true,
          },
        ],
      },
    ],
    // Firebird path: /path → URL gets double-slash (host:port//abs/path) which is correct
    buildUrl: (d) =>
      `firebird://${d.username}:${encodeURIComponent(d.password)}@${d.host}:${d.port}/${d.database}`,
    buildDisplayUrl: (d) =>
      `firebird://${d.username}:***@${d.host}:${d.port}/${d.database}`,
    pasteModePlaceholder:
      "firebird://SYSDBA:password@host:3050//var/lib/firebird/data/mydb.fdb",
  },
  simple({
    id: "actian",
    name: "Actian",
    logoSrc: "/logos/databases/actian.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Hybrid transactional/analytics RDBMS",
    category: "enterprise",
    dialect: "actian",
    port: "27832",
  }),
  simple({
    id: "neon",
    name: "Neon",
    logoSrc: "/logos/databases/neon.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Serverless PostgreSQL",
    category: "relational",
    dialect: "postgresql",
    port: "5432",
    withSchema: true,
  }),
  simple({
    id: "oceanbase",
    name: "OceanBase",
    logoSrc: "/logos/databases/oceanbase.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Distributed relational database",
    category: "relational",
    dialect: "oceanbase",
    port: "2881",
  }),
  simple({
    id: "exasol",
    name: "Exasol",
    logoSrc: "/logos/databases/exasol.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "In-memory MPP analytics database",
    category: "analytics",
    dialect: "exa+pyodbc",
    port: "8563",
  }),
  simple({
    id: "openGauss",
    name: "openGauss",
    logoSrc: "/logos/databases/opengauss.svg",
    logoHeight: "h-7",
    status: "coming_soon",
    description: "Open-source enterprise RDBMS by Huawei",
    category: "relational",
    dialect: "postgresql",
    port: "5432",
    withSchema: true,
  }),
];
