export const SET_DASHBOARD_STATS = "SET_DASHBOARD_STATS" as const;

export const INCREMENT_MESSAGE = "INCREMENT_MESSAGE" as const;

export const DECREMENT_MESSAGE = "DECREMENT_MESSAGE" as const;

export const INCREASE_STORAGE_USAGE = "INCREASE_STORAGE_USAGE" as const;

export const DECREASE_STORAGE_USAGE = "DECREASE_STORAGE_USAGE" as const;

export const INCREMENT_PROJECT = "INCREMENT_PROJECT" as const;

export const DECREMENT_PROJECT = "DECREMENT_PROJECT" as const;

export const INCREMENT_DATASOURCE = "INCREMENT_DATASOURCE" as const;

export const DECREMENT_DATASOURCE = "DECREMENT_DATASOURCE" as const;

export const INCREMENT_TOKENS = "INCREMENT_TOKENS" as const;

export const DECREMENT_TOKENS = "DECREMENT_TOKENS" as const;

export const FETCH_DASHBOARD_STATS_REQUEST =
  "FETCH_DASHBOARD_STATS_REQUEST" as const;

export const FETCH_DASHBOARD_STATS_FAILURE =
  "FETCH_DASHBOARD_STATS_FAILURE" as const;
